name = "plausible"
version = "0.1.0"
defaultTargets = ["Plausible"]
testRunner = "Test"

[[lean_lib]]
name = "Test"

[[lean_lib]]
name = "Plausible"
leanOptions = {linter.missingDocs = false}

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"
