name = "plausible"
version = "0.1.0"
defaultTargets = ["Plausible"]
testRunner = "Test"

[[lean_lib]]
name = "Test"

[[lean_lib]]
name = "Plausible"

[[lean_exe]]
name = "shrink-search-tests"
root = "Test.ShrinkSearch"
